---
- name: Install node and npm packages
  hosts: all
  tasks:
    - name: update yum repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: install node.js and npm
      apt:
        pkg:
          - node.js
          - npm

- name: Deploy node.js app
  hosts: all
  become: yes
  tasks:
    - name: Copy node.js folder to server
      copy:
        src: /root/nodejs-app/app/bootcamp-node-project-1.0.0.tgz
        dest: /root/node-project-1.0.0.tgz
    - name: unpack the node.js tar file
      unarchive: 
        src: /root/node-project-1.0.0.tgz
        dest: /root/
        remote_src: yes
